name: Generate Client

on:
  schedule:
    - cron: '5 11 * * *' # Runs at 11:05 UTC daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download OpenAPI specification
        run: |
          curl -fSL https://esi.evetech.net/latest/swagger.json -o swagger.json
          if [ ! -f swagger.json ]; then
            echo "swagger.json was not downloaded!"
            exit 1
          fi
      - name: Generate Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-url: swagger.json
          command-args: --minimal-update --additional-properties=supportsES6=true,npmName=eve-esi-client-ts,npmVersion=1.0.0
      - name: Commit new client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv typescript-axios-client/* .
          rm -rf typescript-axios-client
          git config --global user.name 'steven-cmy'
          git config --global user.email '4248629+steven-cmy@users.noreply.github.com'
          git add *
          git commit -am "Update typescript client"
          git push
