# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Generate Client

on:
  schedule:
    - cron: '5 11 * * *' # Runs at 11:05 UTC daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-url: https://esi.evetech.net/latest/swagger.json
      - name: Commit new client
        run: |
          git config --global user.name 'steven-cmy'
          git config --global user.email '4248629+steven-cmy@users.noreply.github.com'
          git add *
          git commit -am "Update typescript client"
          git push
